### ISSUE TITLE
LinAlgError in Python 3.7

### ISSUE THREAD

**Issue by tgsmith61591** [tgsmith61591/pmdarima#74]
#### Description

In working towards supporting Python 3.7, I'm encountering a cryptic `LinAlgError` on the Canova-Hansen test that I can't replicate outside of CI environments.

#### Steps/Code to Reproduce

I can't reproduce outside of specific CI environments. Here is exactly the code being run in [the circle job](https://circleci.com/gh/tgsmith61591/pmdarima/373):

```yaml
  cpython37:
    docker:
      - image: python:3.7
    working_directory: ~/pmdarima
    steps:
    - checkout
    - run: make develop
    - run: make test-unit
```

And here is code to run the same exact code in your own docker container (which doesn't reproduce the error 😡):

```bash
$ docker pull python:3.7
$ docker run -it python:3.7 /bin/bash
$ git clone -b py37 https://github.com/tgsmith61591/pmdarima && cd pmdarima
$ make develop
$ make test-unit
```

#### Expected Results

1. This error shouldn't occur
2. If this error does occur, it should happen in both environments, but it doesn't.

I'll dig into the Canova-Hansen test to see if anything funky is going on, but this strikes me more as a numpy/scipy versioning issue than anything else... I believe this is also related to #1, which, funny enough, we dismissed as being due to Numpy versioning as well.

**PRs are of course always welcome**. You may want to branch the WIP branch I currently have going on `py37`, if you so choose..
